name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15.x'

      - name: Install dependencies
        run: yarn
  
      - name: Build
        run: yarn build
  
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
      
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn
  
      - name: Build
        run: yarn build
      
      - name: Simple deploy with git
        uses: rdarida/simple-github-pages-deploy-action@v1
